stages:
  - build
  - test
  - docker-image
  - docker-container
build:
  script: "npm install"
  stage: build
test:
  dependencies:
    - build
  before_script:
    - "npm install"
  script: "npm test"
  stage: test
docker-image:
  dependencies:
    - test
  before_script:
    - "docker stop rlstop-frontend | true & docker container rm rlstop-frontend | true"
    - "docker image rm rlstop-frontend | true"
    -  "npm install"
  script: "docker build -t rlstop-frontend ."
  stage: docker-image
docker-container:
  dependencies:
    - docker-image
  script: "docker run -it -p 3000:3000 --name rlstop-frontend --network rlstop -d rlstop-frontend"
  stage: docker-container




